import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
const root='attached_assets/characters/human',jobs=['warrior','wizard','scout','herbalist'];
const paths=Object.fromEntries([
 ...['male','female'].flatMap(model=>['neutral','hair','eyes','skin'].map(channel=>[`${model}-${channel}`,`${root}/v1/recolor/${channel==='neutral'?`neutral/human-${model}-front.png`:`masks/human-${model}-front-${channel}.png`}`])),
 ...jobs.map(job=>[job,`${root}/static-starters-v1/source/${job}.png`]),
 ['empty-bodies',`${root}/static-starters-v1/source/empty-bodies.png`],
]);
const urls=Object.fromEntries(Object.entries(paths).map(([key,path])=>[key,'data:image/png;base64,'+readFileSync(path).toString('base64')]));
const result=await build({entryPoints:['scripts/avatar/static-workshop/app.ts'],bundle:true,write:false,format:'iife',target:'es2020',minify:true});
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Static starters 02 · QuestAcademy Workshop</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f0e6;color:#2e332f;font:15px/1.5 system-ui,sans-serif}header{padding:20px 28px;border-bottom:1px solid #d8d8c9;background:#fffcf4}h1,h2,p{margin:0}header small{letter-spacing:.13em;text-transform:uppercase;color:#65715b}h1{font:600 29px/1.3 Georgia,serif;margin:5px 0}header p{color:#667064;max-width:800px}.layout{max-width:1220px;margin:auto;display:grid;grid-template-columns:280px 1fr;gap:24px;padding:24px}aside{align-self:start;background:#fffcf4;border:1px solid #d8d8c9;border-radius:14px;padding:22px}h2{font:600 24px Georgia,serif;margin-bottom:20px}label{display:block;font-weight:600;font-size:13px;margin:15px 0}select{font:inherit;display:block;width:100%;padding:10px 9px;margin-top:6px;border:1px solid #b7bfb1;border-radius:7px;background:white;color:#2e332f}.hint{font-size:13px;color:#64705d;margin:16px 0}dl{border-top:1px solid #d8d8c9;padding-top:16px;font-size:13px;margin:0}dt{color:#64705d;margin-top:8px}dd{margin:0;font-weight:600}button{font:inherit;cursor:pointer;border:1px solid #b7bfb1;border-radius:8px;background:#fffcf4;color:#2e332f;padding:9px 12px}button:focus-visible,select:focus-visible{outline:3px solid #8aa977;outline-offset:3px}#download{margin-top:20px;width:100%;background:#315644;color:white;border-color:#315644}.stage{background:radial-gradient(ellipse at center,#fffdf6 15%,#e7e9dc 100%);border:1px solid #d8d8c9;border-radius:16px;text-align:center;min-width:0;position:relative;padding:8px 16px 16px}.badge{position:absolute;top:16px;left:16px;font-size:11px;font-weight:600;letter-spacing:.07em;text-transform:uppercase;background:#fffdf6;padding:6px 10px;border-radius:20px;color:#66725c}#avatar{display:block;height:550px;max-width:100%;object-fit:contain;margin:auto;width:339px}.status{font-size:12px;color:#64705d}.compare{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:16px}.compare button{padding:6px;overflow:hidden;font-size:12px}.compare button[aria-pressed=true]{border:2px solid #315644;background:#e4eadc}.compare canvas{display:block;width:100%;height:160px;object-fit:contain}footer{font-size:12px;color:#64705d;padding:0 24px 24px;max-width:1220px;margin:auto}@media(max-width:680px){header{padding:16px}.layout{padding:14px;grid-template-columns:1fr;gap:14px}aside{display:grid;grid-template-columns:1fr 1fr;gap:0 14px;padding:16px}aside h2,aside .hint,aside dl,#download{grid-column:1/-1}aside h2{margin-bottom:0}label{margin:7px 0}#avatar{height:480px}.compare{gap:6px}.compare canvas{height:125px}.badge{position:static;display:inline-block}}
</style></head><body><header><small>Bookwyrm · QuestAcademy workshop</small><h1>Static starter avatars</h1><p>Front-facing paperdolls · Review 02 · Neck and headwear fit · All jobs, one shared appearance.</p></header><div class="layout"><aside><h2>Make it yours</h2><label>Job<select id="job" aria-label="Job"></select></label><label>Body model<select id="model" aria-label="Body model"><option value="human-male-v1">Male</option><option value="human-female-v1">Female</option></select></label><label>Hair<select id="hair" aria-label="Hair"></select></label><label>Eyes<select id="eyes" aria-label="Eyes"></select></label><label>Skin<select id="skin" aria-label="Skin"></select></label><p class="hint">Change a color, then switch jobs: every outfit uses your latest choice.</p><dl><dt>Outfit</dt><dd id="clothing"></dd><dt>Headwear</dt><dd id="headwear"></dd><dt>Character’s right hand · viewer’s left</dt><dd id="right-hand"></dd><dt>Character’s left hand · viewer’s right</dt><dd id="left-hand"></dd></dl><p class="hint" id="weapon-status"></p><button id="download" type="button">Download this avatar</button></aside><section aria-label="Avatar preview"><div class="stage"><span class="badge">Static art · awaiting approval</span><canvas id="avatar" role="img" aria-label="Avatar"></canvas><h2 id="job-title" style="margin:0"></h2><p class="status" id="status" role="status"></p></div><div class="compare" aria-label="Compare starter jobs">${jobs.map(j=>`<button id="choose-${j}" type="button" aria-pressed="false"><canvas id="compare-${j}" width="240" height="390" aria-hidden="true"></canvas>${j[0].toUpperCase()+j.slice(1)}</button>`).join('')}</div></section></div><footer>Scout arrows sit over the character’s right shoulder. This review changes appearance only; it does not change student records or combat equipment.</footer><script>window.STATIC_STARTER_ASSETS=${JSON.stringify(urls)};</script><script>${result.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')}</script></body></html>`;
mkdirSync('workshop/site/previews',{recursive:true});
const path='workshop/site/previews/static-starters-02.html';
if(Buffer.byteLength(html)>25*1024*1024)throw new Error('Preview exceeds workshop upload limit');
writeFileSync(path,html);
writeFileSync(`${root}/static-starters-v1/manifest.json`,JSON.stringify({id:'static-starters-v1',status:'workshop-review',revision:2,date:'2026-10-05',renderer:'shared/avatar/static-renderer.ts',fits:'shared/avatar/static-catalog.ts',sources:Object.fromEntries(Object.entries(paths).map(([key,path])=>[key,{path,sha256:createHash('sha256').update(readFileSync(path)).digest('hex')}])),preview:{path,bytes:Buffer.byteLength(html),sha256:createHash('sha256').update(html).digest('hex')}},null,2)+'\n');
console.log(`${path} (${(Buffer.byteLength(html)/1024/1024).toFixed(2)} MiB)`);
